language: node_js
node_js:
- 6.10.3
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE spoke_test;' -U postgres
- psql -c "CREATE USER spoke_test WITH PASSWORD 'spoke_test';" -U postgres
- psql -c 'GRANT ALL PRIVILEGES ON DATABASE spoke_test TO spoke_test;' -U postgres
deploy:
  provider: lambda
  function_name: spoke-stage
  region: us-west-1
  role: arn:aws:iam::756917843633:role/service-role/test_python
  runtime: nodejs6.10
  handler_name: handler
  module_name: lambda
  timeout: 300
  memory_size: 512
  access_key_id: AKIAITZUUGIJNKLB4PHA
  secret_access_key:
    secure: "CKlCm5iBsBAGmCrfwue/VByX5VLJqo7CrURo+7BnSHZ9Ayo1x0lftpl/kR3b40OwSpRdt+cTKtK+hOSZU4OpOA/OGJVBFqyLcNBdbzL45GQ0JcXiBNXHxSLgo2W17AsFRGCva4WMC3tNyQz1cBF/wW52B/RyrMIA4aKNzmBsurCk1TCYpXqayEBrD96xKFuWZ/uxbvIlTJA+m8GmpqAbGEdxZztVaXJ4aRk4D2vTkprsd3nfHGG/HWJ4IpAIF4J3SQifQJaHR4aNZu4gSE+ZCxOEUGYOXDPdeIUMB1b9Xb8UXqg3c5VFPP5axplZXpROpgOaXW5mhIzIg139Fr/VU7nUhDW07AhTV8Ti4X77V/A7A7Lmp92RB2T0QPTRmoaRJ8XjblUapAZPWiJmn0IQLQR8Nh0tCLscaPY8c9opLasx4QXc48XtK/tcIuZG+NfpbG8N2y5vwYdwIqbiysw0kDxWPO3wbu+cQ9GERkpq/Jnnkdoi65FcwArFKavc61V9lEqofvSsgJgNRF1AH6JP4PsnrR1wikc7Vi1NDAbLGcUupiAxFbOfTgGGbfA9BSh42z9RVqHwW6I9PJlcx2kFqmk8ncloTEqp5d7tO0ohYA/wRD+ji8KPe2H9M3iARXePE0fAebtQ34pwMJJ1nrNvSICAesH7+Cdy8gWFUjad7nU="
  on:
    branch: auto-deploy-stage
